// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SmoothTouchMove","status":true,"description":"on touch move, player can through events under the player","parameters":{}}
];
